-- DÖVLƏT SEKTORU ÜÇÜN NET SALARY
CREATE OR REPLACE PROCEDURE return_net_salary(gross_salary NUMBER) IS
Net_SALARY NUMBER:=0;
VERGI NUMBER := 0;
BEGIN
  SELECT GROSS_SALARY - VERGI AS NET_SALARY, VERGI INTO NET_SALARY, VERGI FROM ( 
  SELECT
  CASE
    WHEN GROSS_SALARY > 2500 THEN 
    CASE 
        WHEN GROSS_SALARY < 8000 THEN 350 + (GROSS_SALARY -2500)*0.25 + GROSS_SALARY*0.02 + GROSS_SALARY*0.03
        WHEN GROSS_SALARY > 8000 THEN 350 + (GROSS_SALARY -2500)*0.25 + 160+ (GROSS_SALARY-8000)*0.005 + GROSS_SALARY*0.03
    END
    WHEN GROSS_SALARY < 2500 THEN  GROSS_SALARY*0.02 + GROSS_SALARY*0.03 + (GROSS_SALARY-200)*0.14
   END AS VERGI FROM DUAL S)  w;
DBMS_OUTPUT.PUT_LINE('NET SALARY :' || NET_SALARY || ' ' || 'VERILEN VERGI: ' || VERGI);
END;
/
EXEC RETURN_NET_SALARY(7000);
EXEC RETURN_NET_SALARY(&SALARY);

--ÖZƏL SEKTOR ÜÇÜN NET SALARY
CREATE OR REPLACE PROCEDURE return_net_salary(gross_salary NUMBER) IS
Net_SALARY NUMBER:=0;
BEGIN
  SELECT GROSS_SALARY - VERGI AS NET_SALARY INTO NET_SALARY FROM ( SELECT CASE
  WHEN GROSS_SALARY>8000 THEN GROSS_SALARY*0.14 + (80+ (GROSS_SALARY-8000)*0.5)+ (6+ (GROSS_SALARY-200)*0.1)
  WHEN GROSS_SALARY > 200 THEN (6+ (GROSS_SALARY-200)*0.1) + (GROSS_SALARY*0.02)/2 
  WHEN GROSS_SALARY < 200 THEN GROSS_SALARY*0.03 + (GROSS_SALARY* 0.02)/2 
  END AS VERGI,S.* FROM DUAL s)  w;
DBMS_OUTPUT.PUT_LINE('NET SALARY :' || NET_SALARY);
END;
/
EXEC RETURN_NET_SALARY(7000);
EXEC RETURN_NET_SALARY(9700);
