# Tasks
Big data taskları
CREATE USER USER4 IDENTIFIED BY "1234";
GRANT CREATE SESSION TO USER4;
GRANT UNLIMITED TABLESPACE TO USER4;
ALTER USER USER4 QUOTA UNLIMITED ON USERS;
GRANT SELECT, INSERT , UPDATE, DELETE ON WEBSITEUSER TO USER4;
GRANT ALL ON WEBSITEUSER TO USER4;
GRANT ALL PRIVILEGES TO USER4;

CREATE TABLE WEBSITEUSER(
USER_ID NUMBER(3) CONSTRAINT W_I_PK PRIMARY KEY,
USER_NAME NVARCHAR2(40) CONSTRAINT W_N_NN NOT NULL UNIQUE,
USER_EMAIL NVARCHAR2(40) CONSTRAINT W_E_NN NOT NULL UNIQUE,
USER_PASSWORD NVARCHAR2(40) CONSTRAINT W_P_NN NOT NULL
);


INSERT INTO WEBSITEUSER VALUES (1,'SAMIR','samir@gmail.com','123456');
INSERT INTO WEBSITEUSER VALUES (2,'ANAR','anar@gmail.com','123456');
INSERT INTO WEBSITEUSER VALUES (3,'TOFIQ','tofiq@gmail.com','123456');

ALTER TABLE WEBSITEUSER RENAME TO WEBSITEDATA;
ALTER TABLE WEBSITEUSER RENAME COLUMN USER_NAME TO USER_ADI;
ALTER TABLE WEBSITEUSER ADD GENDER NVARCHAR2(10);
ALTER TABLE WEBSITEUSER MODIFY GENDER NVARCHAR2(8);
ALTER TABLE WEBSITEUSER DROP COLUMN GENDER;
ALTER TABLE WEBSITEUSER ADD PHONE NUMBER(20);
UPDATE WEBSITEUSER SET WEBSITEUSER.USER_PASSWORD='1234567' WHERE USER_NAME ='SAMIR';
ALTER TABLE WEBSITEUSER RENAME CONSTRAINT SYS_C008320 TO W_P_NN;
ALTER TABLE WEBSITEUSER MODIFY USER_ID PRIMARY KEY;

DELETE FROM WEBSITEUSER WHERE websiteuser.user_id= 1;
DROP TABLE WEBSITEUSER;

SELECT * FROM user_constraints WHERE TABLE_NAME= 'WEBSITEUSER';
SELECT * FROM WEBSITEUSER;
SELECT websiteuser.user_name,websiteuser.user_email FROM websiteuser;
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name ='SAMIR';
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name LIKE 'S%';
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name ='SAMIR' AND websiteuser.user_email = 'samir@gmail.com';
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name IS NOT NULL;












27/02/2023
CREATE TABLE customers (
  customer_id NUMBER(3) PRIMARY KEY,
  customer_name VARCHAR(50),
  customer_email VARCHAR(50)
);

CREATE TABLE orders (
  order_id NUMBER(3) PRIMARY KEY,
  order_date NVARCHAR2(20),
  customer_id NUMBER(3),
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE CASCADE
);

CREATE TABLE addresses (
  address_id NUMBER(3) PRIMARY KEY,
  customer_id NUMBER(3),
  street_address VARCHAR(100),
  FOREIGN KEY (customer_id) REFERENCES customers(customer_id) ON DELETE SET NULL
);

INSERT INTO addresses VALUES(1, 1, '123 Main St');
INSERT INTO addresses VALUES(2, 1, '456 Oak Ave');
INSERT INTO addresses VALUES(3, 2, '789 Pine St' );

INSERT INTO customers VALUES(1, 'John Doe', 'johndoe@example.com');
INSERT INTO customers VALUES(2, 'Jane Doe', 'janedoe@example.com');
INSERT INTO customers VALUES(3, 'Bob Smith', 'bobsmith@example.com');

INSERT INTO orders VALUES(1, 2022-01-01, 1);
INSERT INTO orders VALUES(2, '2022-01-02', 2);
INSERT INTO orders VALUES(3, '2022-01-03', 1);

SELECT * FROM CUSTOMERS;

SELECT * FROM ORDERS;

SELECT * FROM ADDRESSES;

SELECT orders.order_id, orders.order_date, customers.customer_name
FROM orders
INNER JOIN customers
ON orders.customer_id = customers.customer_id WHERE customers.customer_name='John Doe';


SELECT * 
FROM addresses
INNER JOIN customers
ON addresses.customer_id = customers.customer_id 
WHERE customers.customer_name = 'John Doe';

