select * from emp;
select * from mgr_tab;

SELECT * FROM EMP WHERE REGEXP_LIKE(ENAME,'S');

SELECT * FROM EMP WHERE REGEXP_LIKE(ENAME,'^A','i');

SELECT * FROM EMP WHERE REGEXP_LIKE(ENAME,'K$','i');

SELECT * FROM EMP WHERE REGEXP_LIKE(ENAME,'^A|^S','i');

SELECT * FROM EMP WHERE REGEXP_LIKE(ENAME,'L{2}|T{2}','i');

SELECT REGEXP_REPLACE('4024007187788580','(^\d{3})(.*)(\d{4}$)','\1*********\3') FROM DUAL;

SELECT REGEXP_REPLACE('ADNSU','N','B') FROM DUAL;

SELECT REGEXP_REPLACE('DELETING          EXTRA  SPACE','( ){2,}',' ') FROM DUAL;

SELECT REGEXP_REPLACE('','','') FROM DUAL;

SELECT REGEXP_SUBSTR('','','') FROM DUAL;

SELECT REGEXP_SUBSTR('RETURN THE WORD' ,'[[:alpha:]]+', 1,3) FROM DUAL;

SELECT REGEXP_SUBSTR('RETURN THE ALL WORDS','[[:alpha:]]+',1,  LEVEL) FROM DUAL 
CONNECT BY LEVEL <= REGEXP_COUNT('RETURN THE ALL WORDS',' ') +1;

SELECT REGEXP_SUBSTR('RETURNING 3WORDS WITH 2DIGIT','\d+([[:alpha:]]+)',1, LEVEL) FROM DUAL
CONNECT BY LEVEL <= REGEXP_COUNT('RETURNING 3WORDS WITH DIGIT',' ') +1;
