-- trigger, EMPLOYEES tablosunun D_ID alan?n?n bo? veya 0 olmamas?n? kontrol eder.
CREATE OR REPLACE TRIGGER EMPLOYEE_DEPT_CHECK
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
   IF :NEW.D_ID IS NULL OR :NEW.D_ID = 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'Geçersiz bölüm numaras?: ' || :NEW.D_ID);
   END IF;
END;
/
INSERT INTO EMPLOYEES VALUES(22,'CHARLY','SHOW','CHSHOW@MAIL.RU',3000,'7680 Straubel Street',0,5,22,103,TO_DATE('12-01-2020','DD-MM-YYYY'));


CREATE OR REPLACE TRIGGER EMPLOYEE_JOB_CHECK
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.JOB_ID IS NULL OR :NEW.JOB_ID = 0 THEN
          RAISE_APPLICATION_ERROR(-20001, 'Geçersiz ish numaras?: ' || :NEW.JOB_ID);
END IF;
END;
 /
INSERT INTO EMPLOYEES VALUES(22,'CHARLY','SHOW','CHSHOW@MAIL.RU',3000,'7680 Straubel Street',15,5,0,103,TO_DATE('12-01-2020','DD-MM-YYYY'));


CREATE OR REPLACE TRIGGER EMPLOYEE_SALARY_CHECK
BEFORE INSERT OR UPDATE OF E_SALARY ON EMPLOYEES
FOR EACH ROW
BEGIN
   IF :NEW.E_SALARY > 5000 THEN
      RAISE_APPLICATION_ERROR(-20001, 'Maa? 5000 \ büyük olamaz.');
   END IF;
END;
/
INSERT INTO EMPLOYEES VALUES(22,'CHARLY','SHOW','CHSHOW@MAIL.RU',6000,'7680 Straubel Street',15,5,22,103,TO_DATE('12-01-2020','DD-MM-YYYY'));


CREATE TRIGGER EMP_HIGH_EARNER
AFTER INSERT OR UPDATE OR DELETE ON Employees
FOR EACH ROW
BEGIN
  IF NEW.E_SALARY > 2700 THEN
    INSERT INTO HighEarner (E_ID) VALUES (NEW.E_ID);
  END IF;
END;

CREATE TABLE HighEarner (
  E_ID INT PRIMARY KEY,
  E_SALARY NUMBER
);



CREATE OR REPLACE TRIGGER NEW_EMPLOYEE
AFTER INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
   V_NAME EMPLOYEES.E_NAME%TYPE;
   V_SURNAME EMPLOYEES.E_SURNAME%TYPE;
   V_HIRE_DATE EMPLOYEES.HIRE_DATE%TYPE;
BEGIN
   V_NAME := :NEW.E_NAME;
   V_SURNAME := :NEW.E_SURNAME;
   V_HIRE_DATE := :NEW.HIRE_DATE;
   
   INSERT INTO NEW_EMPLOYEE (E_NAME, E_SURNAME, HIRE_DATE)
   VALUES (V_NAME, V_SURNAME, V_HIRE_DATE);
   
   dbms_output.put_line('Yeni çal??an bilgileri kaydedildi.');
END;
/

CREATE TABLE NEW_EMPLOYEE(
E_NAME NVARCHAR2(30),
E_SURNAME NVARCHAR2(30),
HIRE_DATE DATE
);

SELECT * FROM NEW_EMPLOYEE;

DROP TABLE NEW_EMPLOYEE;

SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES VALUES(22,'CHARLY','SHOW','CHSHOW@MAIL.RU',3000,'7680 Straubel Street',15,5,22,103,TO_DATE('12-01-2020','DD-MM-YYYY'));
