CREATE TABLE KITAB(
KITAB_ID NUMBER(3),
KITAB_AD NVARCHAR2(25) CONSTRAINT K_A_NN NOT NULL,
KITAB_YAZICI NVARCHAR2(25) CONSTRAINT K_Y_NN NOT NULL,
KITAB_SAYI NUMBER(3) CONSTRAINT K_S_NN NOT NULL,
CONSTRAINT KITAB_PK PRIMARY KEY (KITAB_ID),--OUTLINE PRIMARY KEY
CONSTRAINT KT_UNI UNIQUE (KITAB_AD,KITAB_YAZICI)--OUTLINE UNIQUE
);
INSERT INTO KITAB VALUES (1,'3 YOLDASH','A.DUMA',4);
INSERT INTO KITAB VALUES (2,'FIZIKA','S.KERIMOV',10);
INSERT INTO KITAB VALUES (3,'SEFILLER','V.HUGO',3);

SELECT* FROM KITAB;

CREATE TABLE TELEBE(
TELEBE_ID NUMBER(3),
TELEBE_AD NVARCHAR2(25) CONSTRAINT T_A_NN NOT NULL,--NOT NULL OUTLINE YAZILA BILMIR
TELEBE_SOYAD NVARCHAR2(25) CONSTRAINT T_SA_NN NOT NULL,
CONSTRAINT TELEBE_PK PRIMARY KEY (TELEBE_ID)--OUTLINE PRIMARY KEY
);

INSERT INTO TELEBE VALUES (1,'ADNAN','PASHAYEV');
INSERT INTO TELEBE VALUES (2,'MURAD','HACIYEV');
INSERT INTO TELEBE VALUES (3,'QENIRE','HUSEYINOVA');
INSERT INTO TELEBE VALUES (4,'SEDEF','TALIBZADE');

SELECT * FROM TELEBE;

CREATE TABLE TELEBE_KITAB(
TK_ID NUMBER(4) CONSTRAINT TK_PK PRIMARY KEY,--INLINE PRIMARY KEY
KT_TELEBE_ID  NUMBER(3),
TK_KITAB_ID NUMBER(3),
CONSTRAINT T_ID_FK FOREIGN KEY (KT_TELEBE_ID) REFERENCES TELEBE(TELEBE_ID),--FOREIGN KEY
CONSTRAINT K_ID_FK FOREIGN KEY (TK_KITAB_ID) REFERENCES KITAB(KITAB_ID)--FOREIGN KEY
);
INSERT INTO TELEBE_KITAB VALUES (5,1,3);

