CREATE TABLE worker (
  id INT PRIMARY KEY,
  name VARCHAR(50),
  salary NUMBER (10),
  PHONE_NUMBER NVARCHAR2(20)
);

INSERT INTO WORKER VALUES (1,'John Smith', 52321.60, '123-456-7890');
INSERT INTO WORKER VALUES (2,'Jane Doe', 63123.50, '234-567-8901');
INSERT INTO WORKER VALUES (3,'Bob Johnson', 452312.20, '345-678-9012');
INSERT INTO WORKER VALUES (4,'Samantha Lee', 724421.55, '456-789-0123');
INSERT INTO WORKER VALUES (5,'Tom Wilson', 552344.22, '567-890-1234');

SELECT * FROM WORKER;
--ROUND TAMA YUVARLAQLASDIRIR
SELECT NAME, ROUND(SALARY) AS ROUND FROM WORKER ;
--ROUND - ILE SOL TERERI DE YUVARLAQLASDIRIR
SELECT NAME ,ROUND(SALARY,-3) AS SAL FROM WORKER;
--FLOOR ASAGI MERTEBEYE YUVARLAQLASDIRIR
SELECT NAME , FLOOR(SALARY) FROM WORKER;
--CEIL YUXARI MERTEBEYE YUVARLAQLASDIRIR
SELECT NAME,CEIL(SALARY) FROM WORKER;
--TRUNC KESR HISSENI ATIR
SELECT NAME,TRUNC(SALARY) FROM WORKER;
SELECT ROUND(1.5),FLOOR(1.9),CEIL(1.1),TRUNC(1.5) FROM DUAL;
--SQRT KOK ALTINA SALIR
SELECT SQRT(25) FROM DUAL;

--AVG EDEDI ORTANI VERIR
SELECT ROUND(AVG(SALARY)) FROM WORKER;
--MEDIAN SIRALAYIR VE ORTADAKI EDEDI VERIR
SELECT MEDIAN(SALARY) FROM WORKER;
--VARRIENCE EDEDI ORTADAN KENARLASMA
SELECT ROUND(VARIANCE(SALARY)) FROM WORKER;
--STD DEVIATION EDEDI ORTADAN STANDART KENARLASMA
SELECT  ROUND(SQRT(VARIANCE(SALARY))) FROM WORKER;

--NTILE CEDVELI HISSELERE BOLUR
SELECT NTILE(3) OVER(ORDER BY SALARY) NTILES, W.* FROM WORKER W;

SELECT NTILES,MAX(SALARY),MIN(SALARY) FROM (
SELECT NTILE(3) OVER(ORDER BY SALARY) NTILES, W.* FROM WORKER W) 
GROUP BY NTILES;

--SUBSTR STRINGIN BIR HISSESINE MURACIET EDE BILIR
SELECT SUBSTR(NAME,1,3) FROM WORKER;
-- SUBSTR SINTAKSIS (SUBSTR(COLUMN_NAME,START_POINT,LENGHT)
SELECT SUBSTR(NAME,3) FROM WORKER;
--INSTR STRINGDE AXTARIS ETMEK UCUNDUR
SELECT INSTR(name,'o') AS WORKER_O FROM WORKER;
--REPLACE STRINGDEKI HISSENI EVEZ EDIR
SELECT REPLACE(S,'HISSE','PARCA') FROM(SELECT 'STRINGDEKI HISSE' S FROM DUAL);


SELECT SUBSTR(REPLACED,1,INSTR(REPLACED,'|',1,1)-1)|| ' ' ||
SUBSTR(replaced, INSTR(replaced, '|', 1, 2)+1,INSTR(replaced, '|', 1, 3)-INSTR(replaced, '|', 1, 2)-1 )|| ' '||
SUBSTR(replaced, INSTR(replaced, '|', 1, 1)+1, INSTR(replaced, '|', 1, 2)-INSTR(replaced, '|', 1, 1)-1) || ' '||
SUBSTR(replaced, INSTR(replaced,'|',1,3)+1,INSTR(replaced,'|',1))
FROM(SELECT REPLACE(IATC,' ','|') AS REPLACED FROM(SELECT 'ISRAIL TELIM AZERBAYCAN MERKEZI'AS IATC FROM DUAL))
