# Tasks
Big data taskları
CREATE USER USER4 IDENTIFIED BY "1234";
GRANT CREATE SESSION TO USER4;
GRANT UNLIMITED TABLESPACE TO USER4;
ALTER USER USER4 QUOTA UNLIMITED ON USERS;
GRANT SELECT, INSERT , UPDATE, DELETE ON WEBSITEUSER TO USER4;
GRANT ALL ON WEBSITEUSER TO USER4;
GRANT ALL PRIVILEGES TO USER4;

CREATE TABLE WEBSITEUSER(
USER_ID NUMBER(3) CONSTRAINT W_I_PK PRIMARY KEY,
USER_NAME NVARCHAR2(40) CONSTRAINT W_N_NN NOT NULL UNIQUE,
USER_EMAIL NVARCHAR2(40) CONSTRAINT W_E_NN NOT NULL UNIQUE,
USER_PASSWORD NVARCHAR2(40) CONSTRAINT W_P_NN NOT NULL
);


INSERT INTO WEBSITEUSER VALUES (1,'SAMIR','samir@gmail.com','123456');
INSERT INTO WEBSITEUSER VALUES (2,'ANAR','anar@gmail.com','123456');
INSERT INTO WEBSITEUSER VALUES (3,'TOFIQ','tofiq@gmail.com','123456');

ALTER TABLE WEBSITEUSER RENAME TO WEBSITEDATA;
ALTER TABLE WEBSITEUSER RENAME COLUMN USER_NAME TO USER_ADI;
ALTER TABLE WEBSITEUSER ADD GENDER NVARCHAR2(10);
ALTER TABLE WEBSITEUSER MODIFY GENDER NVARCHAR2(8);
ALTER TABLE WEBSITEUSER DROP COLUMN GENDER;
ALTER TABLE WEBSITEUSER ADD PHONE NUMBER(20);
UPDATE WEBSITEUSER SET WEBSITEUSER.USER_PASSWORD='1234567' WHERE USER_NAME ='SAMIR';
ALTER TABLE WEBSITEUSER RENAME CONSTRAINT SYS_C008320 TO W_P_NN;
ALTER TABLE WEBSITEUSER MODIFY USER_ID PRIMARY KEY;

DELETE FROM WEBSITEUSER WHERE websiteuser.user_id= 1;
DROP TABLE WEBSITEUSER;

SELECT * FROM user_constraints WHERE TABLE_NAME= 'WEBSITEUSER';
SELECT * FROM WEBSITEUSER;
SELECT websiteuser.user_name,websiteuser.user_email FROM websiteuser;
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name ='SAMIR';
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name LIKE 'S%';
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name ='SAMIR' AND websiteuser.user_email = 'samir@gmail.com';
SELECT * FROM WEBSITEUSER WHERE websiteuser.user_name IS NOT NULL;













