CREATE MATERIALIZED VIEW mv_loan
REFRESH COMPLETE ON DEMAND
AS 
SELECT *
FROM loan
WHERE amount > 8000;
SELECT * FROM MV_LOAN;

CREATE MATERIALIZED VIEW mv_hi
REFRESH COMPLETE ON DEMAND
AS 
SELECT *
FROM loan
WHERE interest_rate > 5;
SELECT * FROM MV_HI;

CREATE MATERIALIZED VIEW mv_loan_high_amount_high_interest
REFRESH COMPLETE ON DEMAND
AS
SELECT *
FROM loan
WHERE amount > 7000 AND interest_rate > 5;
SELECT * FROM mv_loan_high_amount_high_interest;

SELECT * FROM LOAN;

BEGIN
  DBMS_MVIEW.REFRESH('mv_loan');
END;
/
SET SERVEROUT ON;
DROP MATERIALIZED VIEW MV_HI;
DROP MATERIALIZED VIEW MV_LOAN;
DROP MATERIALIZED VIEW mv_loan_high_amount_high_interest;
